"""Document structure/metadata checks. Text style and producer tags are not reliable AI detectors."""
from pathlib import Path
from typing import Any, Dict, List, Tuple
import hashlib, logging, zipfile, io
logger=logging.getLogger(__name__)
class DocumentAnalyzer:
 @staticmethod
 def analyze(file_path: Path, metadata: Dict[str,Any])->Tuple[Dict[str,Any],List[Dict[str,Any]]]:
  p=Path(file_path); ev:List[Dict[str,Any]]=[]
  r={'ai_generation_score':0.0,'manipulation_score':0.0,'ai_model_available':False,'manipulation_model_available':False,'score_semantics':'No validated AI-text/document detector configured; scores are not probabilities.','model_architecture':'Document metadata/structure screening only','file_sha256':None}
  try:
   if not p.is_file(): raise FileNotFoundError(str(p))
   data=p.read_bytes(); r['file_sha256']=hashlib.sha256(data).hexdigest(); ext=p.suffix.lower()
   if ext=='.pdf':
    valid=data.startswith(b'%PDF-'); eof_count=data.count(b'%%EOF'); r['document_format_check']={'pdf_header':valid,'eof_markers':eof_count}
    if not valid: raise ValueError('PDF extension but missing PDF header')
    ev.append({'id':'DOC_EVID_PDF_STRUCTURE','title':'PDF container header checked','category':'File Integrity','severity':'Informational','description':'Basic PDF signature and EOF marker count were checked. These checks do not determine whether content is AI-written or manipulated.','technical_details':f'EOF marker count={eof_count}'})
   elif ext=='.docx':
    with zipfile.ZipFile(io.BytesIO(data)) as z:
     names=set(z.namelist()); core='docProps/core.xml' in names; document='word/document.xml' in names
     if not document: raise ValueError('DOCX package lacks word/document.xml')
     r['document_format_check']={'core_properties_present':core,'document_xml_present':document}
    ev.append({'id':'DOC_EVID_OOXML_STRUCTURE','title':'DOCX package structure checked','category':'File Integrity','severity':'Informational','description':'The OOXML package was opened and its main document part was found. Structure validity does not identify AI authorship.','technical_details':str(r['document_format_check'])})
   elif ext=='.txt':
    text=data.decode('utf-8-sig',errors='replace'); r['document_format_check']={'characters':len(text),'words':len(text.split()),'lines':len(text.splitlines())}
    ev.append({'id':'DOC_EVID_TEXT_STATS','title':'Text statistics extracted','category':'Metadata','severity':'Informational','description':'Basic text statistics were extracted. Entropy or sentence regularity alone cannot reliably identify AI-written text.','technical_details':str(r['document_format_check'])})
   else: raise ValueError(f'Unsupported document extension: {ext}')
   producer=str(metadata.get('Producer / Creator','Not available'))
   if producer!='Not available' and any(t in producer.lower() for t in ('chatgpt','openai','claude','anthropic','gemini','copilot','llm')):
    ev.append({'id':'DOC_EVID_LLM_TAG','title':'Possible AI-related producer metadata marker','category':'AI Generation','severity':'Medium','description':'Producer metadata contains an AI-related string. It can be copied, edited or forged and does not prove the document text was generated by AI.','technical_details':producer[:300]})
   else:
    ev.append({'id':'DOC_EVID_NO_LLM_TAG','title':'No explicit AI producer marker found','category':'Metadata','severity':'Informational','description':'No known AI-related producer marker was found. This does not establish human authorship.','technical_details':producer[:300]})
  except Exception as exc:
   logger.exception('Document inspection failed'); r['analysis_error']=f'{type(exc).__name__}: {exc}'
   ev.append({'id':'DOC_EVID_ERROR','title':'Document inspection failed','category':'System','severity':'Informational','description':'The file could not be inspected reliably; no AI verdict is available.','technical_details':r['analysis_error']})
  return r,ev
